apiVersion: v1
kind: Service
metadata:
  name: jbhinfoapp-service
  annotations:
    # TODO: Fill in with the ARN of your certificate.
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:811127499995:certificate/bae215dc-cd1e-47dc-9b00-d3cf5e736d53
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  selector:
    app: jbhinfoapp
  ports:
  - name: http
    port: 80
    targetPort: jbhinfoapp-port
    nodePort: 30002
  - name: https
    port: 443
    targetPort: jbhinfoapp-port
    nodePort: 30001
  type: LoadBalancer